### ISSUE TITLE
Cannot connect to omi server since PowerShell v6.0.0-beta.3

### ISSUE THREAD

**Issue by darootler** [PowerShell/psl-omi-provider#101]
I just upgraded from PowerShell v6.0.0-beta.2 to PowerShell v6.0.0-beta.3 and since then i am not able to connect from Windows to Linux with PowerShell Remoting:

Steps to reproduce:

On the Linux side:
`sudo apt install powershell omi omi-psrp-server`

On the Windows side:
`$creds = Get-Credential`
`Enter-PSSession -ComputerName HOSTNAME -Credential $creds -Authentication Basic -SessionOption $(New-PSSessionOption -SkipCACheck -SkipCNCheck) -UseSSL`

Logs:
`2017/06/26 11:48:26 [3619,3619] WARNING: null(0): EventId=30058 Priority=WARNING failed to call provider's load with result 1; class: Shell`
`2017/06/26 11:48:26 [3619,3619] WARNING: null(0): EventId=30066 Priority=WARNING failed to open the provider psrpomiprov for class Shell`
`2017/06/26 11:48:26 [3619,3619] ERROR: null(0): EventId=20001 Priority=ERROR Agent _RequestCallback: ProvMgr_NewRequest failed with result 1 !`

Regards
Richard

**Comment by JumpingYang001** [comment]
Looks like this bug fixed in PR #99 , I will verify it tomorrow.

**Comment by JumpingYang001** [comment]
Verified, the PR #99 fixed the issue for remoting from Linux/Mac->Linux/Windows.

**Comment by darootler** [comment]
I just installed PowerShell v6.0.0-beta.4 and i am still running into this issue. Do i have have to do anything else to fix this problem?

Regards
Richard

**Comment by JumpingYang001** [comment]
You need to wait new release package under https://github.com/PowerShell/psl-omi-provider/releases

**Comment by jfanctil** [comment]
I find weird that the powershell package is at beta-7 now and this issue is still there... it's been 5 beta releases that this core-feature (able to do remote commands from Windows to Linux, which is, I think, the main feature for installing powershell on linux...) is broken. It's almost unacceptable...

**Comment by darootler** [comment]
@jfanctil 

That's exactly what i am thinking. On the other hand that's open source and beta, so we have to be patiently.

Regards
Richard

**Comment by JumpingYang001** [comment]
this project was transitioned from OMI team to PowerShell team for serveral months, @daxian-dbw could you help to check this? or can you share with your team lead/manager about this? thanks

**Comment by daxian-dbw** [comment]
There hasn't been a release of psl-omi-provider since the merging of #99. PowerShell team needs to publish a new release and also figure out the process of future releases when there are any changes made to this repository.
/cc @dantraMSFT @SteveL-MSFT

**Comment by darootler** [comment]
Still no working powershell remoting...

Regards
Richard

**Comment by dantraMSFT** [comment]
This should be fixed by https://github.com/PowerShell/psl-omi-provider/releases/tag/v1.4.1-28.

**Comment by darootler** [comment]
When will this version be available in the official repositories?

![pspr](https://user-images.githubusercontent.com/11849583/33062046-3757b484-ce9e-11e7-88da-58369eab2a97.png)

Regards
Richard

**Comment by darootler** [comment]
@dantraMSFT 

If you look inside this package https://packages.microsoft.com/ubuntu/16.04/prod/dists/xenial/main/binary-amd64/Packages.gz you'll find omi-psrp-server version 1.0.0.18

Do i have the false repository set up?

Regards
Richard

**Comment by dantraMSFT** [comment]
The packages are available now.
